### ISSUE TITLE
SetEditorFormatter causes Translate option to stop working

### ISSUE THREAD

**Issue by michaellwest** [michaellwest/sitecore-codeeditor#16]
09:24 AM on May 28, 2015

Hi Michael,

According to the info on marketplace, this module should be compatible with sitecore version 7.2
After upgrading our solution to sitecore 7.2 with the latest version of the code editor, we found that the "translate" option in the content editor ribbon no longer works.
When we discussed this with Sitecore support, this was their answer: 

During my investigation I've found that your issue is caused by the Code Editor shared source module. I've installed it in my environment and reproduced the issue. After disabling the SetEditorFormatter processor added by this module to the renderContentEditor pipeline the "Translate" button starts working as expected.

Do you have any idea how we can fix this issue and still be able to use the code editor?

Cheers
Jeroen

**Comment by michaellwest** [comment]
Fixed.

**Comment by jvanbortel** [comment]
Great! :-)

**Comment by michaellwest** [comment]
Not sure if this arrived in the previous release but it's there now.
