### ISSUE TITLE
Upgrade to support Sitecore 8

### ISSUE THREAD

**Issue by michaellwest** [michaellwest/sitecore-codeeditor#17]
Need to provide an updated build to support Sitecore 8.x. 

Need to ensure features such as the autocomplete and syntax highlighting still work.

**Comment by AdamNaj** [comment]
What do you mean?

**Comment by AdamNaj** [comment]
Oh wow! I haven't realised it's code-editor and not PowerShell :)

**Comment by wbthrasher** [comment]
FYI, I am currently successfully using 1.6.0 on Sitecore 8.1.

**Comment by michaellwest** [comment]
Time to validate the UI in 8.1

**Comment by michaellwest** [comment]
Fixed.
