### ISSUE TITLE
Add context menu to edit code item and create new

### ISSUE THREAD

**Issue by michaellwest** [michaellwest/sitecore-codeeditor#19]
Context Menu should show the same dialog as the Edit Code command on the field.

**Comment by michaellwest** [comment]
![image](https://cloud.githubusercontent.com/assets/933163/17504718/fb887c30-5dc0-11e6-8870-de0dfc0d0dfc.png)

**Comment by AdamNaj** [comment]
I wonder if you've checked it with both CE and SPE deployed on the same environment. I think the way this is implemented they might conflict.

**Comment by michaellwest** [comment]
I'll no doubt have a look before I'm doing with it. Thanks for the reminder.

**Comment by michaellwest** [comment]
Implemented. The Insert Options are disabled by default until we can figure out how to prevent conflict with SPE.
